[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lead_scoring"
version = "0.1.0"
description = "End-to-end lead conversion scoring pipeline"
authors = [{name = "Bilal"}]
requires-python = ">=3.9"
dependencies = []
